version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 10.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: aegir
    versions:
    - 30.3.0
    - 31.0.0
    - 31.0.1
    - 31.0.3
    - 31.0.4
    - 32.0.2
    - 32.1.0
    - 32.2.0
    - 33.0.0
  - dependency-name: uint8arrays
    versions:
    - 2.0.5
    - 2.1.0
    - 2.1.2
    - 2.1.3
    - 2.1.4
  - dependency-name: multibase
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.4
  - dependency-name: err-code
    versions:
    - 3.0.0
    - 3.0.1
  - dependency-name: varint
    versions:
    - 6.0.0
